/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package halykacademy;

import java.util.Scanner;

public class App {
    //Done by Askar Aytkazin
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.println("Enter number of rows: ");
        int rows = sc.nextInt();

        printTree(rows);
        printRoot(rows);
    }

    //prints pyramid of tree
    public static void printTree(int rows) {
        int space = rows - 1;
        for (int i = 1; i <= rows; i++) {
            //printing spaces before stars
            for (int j = 0; j <= space; j++) {
                System.out.print(" ");
            }
            space -= 1;

            //printing stars
            for (int j = 1; j <= 2 * i - 1; j++) {
                System.out.print("*");
            }
            System.out.println();
        }
    }

    //prints root of the tree (adjust to tree size)
    public static void printRoot(int rows) {
        int count, space, star_cnt;
        //every 5 rows adds one root line
        if (rows % 5 == 0) {
            count = rows / 5;
        } else {
            count = rows / 5 + 1;
        }

        //checks how many spaces and stars needed for root
        if (rows % 2 == 0) {
            space = rows / 2 + rows / 4;
            star_cnt = rows / 2;
        } else {
            space = rows / 2 + rows / 4 + 1;
            star_cnt = rows / 2 + 1;
        }

        //prints spaces
        for (int i = 1; i <= count; i++) {
            for (int j = 0; j <= space; j++) {
                System.out.print(" ");
            }

            //prints root
            for (int j = 1; j <= star_cnt; j++) {
                System.out.print("*");
            }
            System.out.println();
        }
    }

}


